### ISSUE TITLE
GLS trackPackages return empty statuses

### ISSUE THREAD

**Issue by eugeene** [inspirum/balikobot-php#3]
## Detailed description

When tracking GLS packages, statuses returned by trackPackages() are always empty.

## Possible implementation

the issue is due to this part of code:

        if (empty($response[0])) {
            throw new BadRequestException($response);
        }

**$response[0]** can be empty and thus will throw an exception, crude (don't now if good) solution is to check **$response[1]** being set:

        if (empty($response[0])) {
			if(empty($response[1])) {
				throw new BadRequestException($response);
			}

			$response[0] = $response[1];
        }

**Comment by tomas-novotny** [comment]
There is problem with response data from API. For **GLS** shipper **TRACK** request API returns only last package statuses. In your case, there are data only for second package with index [1].

Method doesn't throw exception now (fixed in [v3.1.0](https://github.com/inspirum/balikobot-php/releases/tag/v3.1.0), it returns empty array for missing indexes instead.

The response data for multiple packages for other shippers are correct. Response from **TRACK_STATUS** request for **GLS** shipper with multiple packages is also correct. 

I recommend contacting Balikobot support to resolve this issue.
